#!/usr/bin/env bash

curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=2000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fapache%2Fnutch.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=3000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fapache%2Fparquet-mr.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=4000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fapache%2Fzookeeper.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'

curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=5000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fspring-projects%2Fspring-security.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=6000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fapache%2Fkafka.git%3Fbranch%3Dtrunk&branch=trunk&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=7000&dfScmUrl=https%3A%2F%2Fgithub.com%2FJetBrains%2Fkotlin-native.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'

curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=8000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fspring-projects%2Fspring-boot.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=9000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fspring-projects%2Fspring-framework.git%3Fbranch%3Dmaster&branch=master&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'repositoryId=10000&dfScmUrl=https%3A%2F%2Fgithub.com%2Fapache%2Ftomcat.git%3Fbranch%3Dtrunk&branch=trunk&replayHistory=true' 'http://localhost:8080/api/v1.1/repositories'
